//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "backtest_logs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backtest_id: i32,
    pub slate_id: i32,
    pub log_timestamp: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::backtests::Entity",
        from = "Column::BacktestId",
        to = "super::backtests::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Backtests,
    #[sea_orm(
        belongs_to = "super::slates::Entity",
        from = "Column::SlateId",
        to = "super::slates::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Slates,
}

impl Related<super::backtests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backtests.def()
    }
}

impl Related<super::slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
