//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "backtest_lineups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backtest_id: i32,
    pub slate_id: i32,
    pub lineup_number: i32,
    pub p1: String,
    pub p2: String,
    pub c: String,
    pub first: String,
    pub second: String,
    pub third: String,
    pub ss: String,
    pub of1: String,
    pub of2: String,
    pub of3: String,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub p1_fp: Decimal,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub p2_fp: Decimal,
    pub c_fp: i32,
    pub first_fp: i32,
    pub second_fp: i32,
    pub third_fp: i32,
    pub ss_fp: i32,
    pub of1_fp: i32,
    pub of2_fp: i32,
    pub of3_fp: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub total_fp: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_results::Entity")]
    BacktestResults,
    #[sea_orm(
        belongs_to = "super::backtests::Entity",
        from = "Column::BacktestId",
        to = "super::backtests::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Backtests,
    #[sea_orm(
        belongs_to = "super::slates::Entity",
        from = "Column::SlateId",
        to = "super::slates::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Slates,
}

impl Related<super::backtest_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestResults.def()
    }
}

impl Related<super::backtests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backtests.def()
    }
}

impl Related<super::slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
