//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "backtests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub contest_serial: i32,
    pub stacking_type: String,
    pub hitter_proj_id: i32,
    pub pitcher_proj_id: i32,
    pub num_overlap: i32,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub hitter_exp: Decimal,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub pitcher_exp: Decimal,
    pub teamstack1_id: String,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub teamstack2_exp: Decimal,
    #[sea_orm(column_type = "Decimal(Some((3, 2)))")]
    pub teamstack3_exp: Decimal,
    pub reopt_seq_id: i32,
    pub season_year: String,
    pub has_lineups: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_contest_summaries::Entity")]
    BacktestContestSummaries,
    #[sea_orm(has_many = "super::backtest_lineups::Entity")]
    BacktestLineups,
    #[sea_orm(has_many = "super::backtest_logs::Entity")]
    BacktestLogs,
    #[sea_orm(has_many = "super::backtest_summaries::Entity")]
    BacktestSummaries,
    #[sea_orm(has_many = "super::backtests_complete::Entity")]
    BacktestsComplete,
    #[sea_orm(
        belongs_to = "super::contest_list_parameters::Entity",
        from = "Column::ContestSerial",
        to = "super::contest_list_parameters::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ContestListParameters,
    #[sea_orm(
        belongs_to = "super::projections::Entity",
        from = "Column::HitterProjId",
        to = "super::projections::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Projections2,
    #[sea_orm(
        belongs_to = "super::projections::Entity",
        from = "Column::PitcherProjId",
        to = "super::projections::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Projections1,
}

impl Related<super::backtest_contest_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestContestSummaries.def()
    }
}

impl Related<super::backtest_lineups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestLineups.def()
    }
}

impl Related<super::backtest_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestLogs.def()
    }
}

impl Related<super::backtest_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestSummaries.def()
    }
}

impl Related<super::backtests_complete::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestsComplete.def()
    }
}

impl Related<super::contest_list_parameters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestListParameters.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
