//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "backtest_contest_summaries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backtest_id: i32,
    pub strategy_id: i32,
    pub slate_id: i32,
    pub contest_id: String,
    pub slate: String,
    pub number_of_games: i32,
    pub max_entries: i32,
    pub total_entries: i32,
    #[sea_orm(column_type = "Double")]
    pub entry_fee: f64,
    pub total_prizes: i32,
    pub total_cost: i32,
    pub profit: i32,
    #[sea_orm(column_type = "Double")]
    pub roi_percent: f64,
    #[sea_orm(column_type = "Double")]
    pub profit_margin_percent: f64,
    pub num_placed_lineups: i32,
    #[sea_orm(column_type = "Double")]
    pub winning_score: f64,
    #[sea_orm(column_type = "Double")]
    pub our_top_score: f64,
    pub our_top_rank: i32,
    pub total_first_places: i32,
    pub total_top_5: i32,
    pub total_top_10: i32,
    pub total_top_25: i32,
    pub total_top_50: i32,
    pub total_top_100: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::backtest_strategies::Entity",
        from = "Column::StrategyId",
        to = "super::backtest_strategies::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BacktestStrategies,
    #[sea_orm(
        belongs_to = "super::backtests::Entity",
        from = "Column::BacktestId",
        to = "super::backtests::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Backtests,
    #[sea_orm(
        belongs_to = "super::contest_data::Entity",
        from = "Column::ContestId",
        to = "super::contest_data::Column::ContestId",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    ContestData,
    #[sea_orm(
        belongs_to = "super::slates::Entity",
        from = "Column::SlateId",
        to = "super::slates::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Slates,
}

impl Related<super::backtest_strategies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestStrategies.def()
    }
}

impl Related<super::backtests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backtests.def()
    }
}

impl Related<super::contest_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestData.def()
    }
}

impl Related<super::slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
