//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "backtest_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub slate_id: Option<i32>,
    pub run: i32,
    pub scratched: i32,
    pub duplicate: i32,
    pub game_id: Option<i32>,
    pub player_id: Option<i32>,
    pub team_id: Option<i32>,
    pub opp_id: Option<i32>,
    pub pos: String,
    pub salary: i32,
    pub locked: i32,
    #[sea_orm(column_type = "Decimal(Some((8, 2)))")]
    pub actual_fp: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::games::Entity",
        from = "Column::GameId",
        to = "super::games::Column::GameId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Games,
    #[sea_orm(has_many = "super::hitter_projections::Entity")]
    HitterProjections,
    #[sea_orm(has_many = "super::pitcher_projections::Entity")]
    PitcherProjections,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerId",
        to = "super::players::Column::PlayerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players,
    #[sea_orm(
        belongs_to = "super::slates::Entity",
        from = "Column::SlateId",
        to = "super::slates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Slates,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::OppId",
        to = "super::teams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams2,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::TeamId",
        to = "super::teams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams1,
}

impl Related<super::games::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Games.def()
    }
}

impl Related<super::hitter_projections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HitterProjections.def()
    }
}

impl Related<super::pitcher_projections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PitcherProjections.def()
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Players.def()
    }
}

impl Related<super::slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
