//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "backtest_summaries")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backtest_id: i32,
    pub contests: i32,
    pub slates: i32,
    pub total_prizes: i32,
    pub total_cost: i32,
    pub profit: i32,
    #[sea_orm(column_type = "Double")]
    pub roi_percent: f64,
    #[sea_orm(column_type = "Double")]
    pub profit_margin_percent: f64,
    pub total_first_places: i32,
    pub total_top_5: i32,
    pub total_top_10: i32,
    pub total_top_25: i32,
    pub total_top_50: i32,
    pub total_top_100: i32,
    pub game_3_count: i32,
    pub game_3_profit: i32,
    pub game_3_first_places: i32,
    pub game_3_top_5: i32,
    pub game_3_top_10: i32,
    pub game_3_top_25: i32,
    pub game_4_count: i32,
    pub game_4_profit: i32,
    pub game_4_first_places: i32,
    pub game_4_top_5: i32,
    pub game_4_top_10: i32,
    pub game_4_top_25: i32,
    pub game_5_count: i32,
    pub game_5_profit: i32,
    pub game_5_first_places: i32,
    pub game_5_top_5: i32,
    pub game_5_top_10: i32,
    pub game_5_top_25: i32,
    pub game_6_count: i32,
    pub game_6_profit: i32,
    pub game_6_first_places: i32,
    pub game_6_top_5: i32,
    pub game_6_top_10: i32,
    pub game_6_top_25: i32,
    pub game_7_count: i32,
    pub game_7_profit: i32,
    pub game_7_first_places: i32,
    pub game_7_top_5: i32,
    pub game_7_top_10: i32,
    pub game_7_top_25: i32,
    pub game_8_count: i32,
    pub game_8_profit: i32,
    pub game_8_first_places: i32,
    pub game_8_top_5: i32,
    pub game_8_top_10: i32,
    pub game_8_top_25: i32,
    pub game_9_count: i32,
    pub game_9_profit: i32,
    pub game_9_first_places: i32,
    pub game_9_top_5: i32,
    pub game_9_top_10: i32,
    pub game_9_top_25: i32,
    pub game_10_count: i32,
    pub game_10_profit: i32,
    pub game_10_first_places: i32,
    pub game_10_top_5: i32,
    pub game_10_top_10: i32,
    pub game_10_top_25: i32,
    pub game_11_count: i32,
    pub game_11_profit: i32,
    pub game_11_first_places: i32,
    pub game_11_top_5: i32,
    pub game_11_top_10: i32,
    pub game_11_top_25: i32,
    pub game_12_count: i32,
    pub game_12_profit: i32,
    pub game_12_first_places: i32,
    pub game_12_top_5: i32,
    pub game_12_top_10: i32,
    pub game_12_top_25: i32,
    pub game_13_count: i32,
    pub game_13_profit: i32,
    pub game_13_first_places: i32,
    pub game_13_top_5: i32,
    pub game_13_top_10: i32,
    pub game_13_top_25: i32,
    pub game_14_count: i32,
    pub game_14_profit: i32,
    pub game_14_first_places: i32,
    pub game_14_top_5: i32,
    pub game_14_top_10: i32,
    pub game_14_top_25: i32,
    pub game_15_count: i32,
    pub game_15_profit: i32,
    pub game_15_first_places: i32,
    pub game_15_top_5: i32,
    pub game_15_top_10: i32,
    pub game_15_top_25: i32,
    pub strategy_id: i32,
    pub date_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::backtest_strategies::Entity",
        from = "Column::StrategyId",
        to = "super::backtest_strategies::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BacktestStrategies,
    #[sea_orm(
        belongs_to = "super::backtests::Entity",
        from = "Column::BacktestId",
        to = "super::backtests::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Backtests,
    #[sea_orm(
        belongs_to = "super::dates::Entity",
        from = "Column::DateId",
        to = "super::dates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dates,
}

impl Related<super::backtest_strategies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestStrategies.def()
    }
}

impl Related<super::backtests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backtests.def()
    }
}

impl Related<super::dates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
