//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "backtest_contest_list")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub contest_serial: i32,
    pub slate_id: i32,
    pub contest_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contest_data::Entity",
        from = "Column::ContestId",
        to = "super::contest_data::Column::ContestId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ContestData,
    #[sea_orm(
        belongs_to = "super::contest_list_parameters::Entity",
        from = "Column::ContestSerial",
        to = "super::contest_list_parameters::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ContestListParameters,
    #[sea_orm(
        belongs_to = "super::slates::Entity",
        from = "Column::SlateId",
        to = "super::slates::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Slates,
}

impl Related<super::contest_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestData.def()
    }
}

impl Related<super::contest_list_parameters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestListParameters.def()
    }
}

impl Related<super::slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
