//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "backtest_strategies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_contest_summaries::Entity")]
    BacktestContestSummaries,
    #[sea_orm(has_many = "super::backtest_results::Entity")]
    BacktestResults,
    #[sea_orm(has_many = "super::backtest_summaries::Entity")]
    BacktestSummaries,
}

impl Related<super::backtest_contest_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestContestSummaries.def()
    }
}

impl Related<super::backtest_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestResults.def()
    }
}

impl Related<super::backtest_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestSummaries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
