//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "backtests_complete")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backtest_id: i32,
    pub year_id: i32,
    pub summary_created: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::backtests::Entity",
        from = "Column::BacktestId",
        to = "super::backtests::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Backtests,
    #[sea_orm(
        belongs_to = "super::years::Entity",
        from = "Column::YearId",
        to = "super::years::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Years,
}

impl Related<super::backtests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backtests.def()
    }
}

impl Related<super::years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Years.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
