//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contest_list_parameters")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub small_contest_max_entries: Option<i32>,
    pub small_contest_min_top_prize: Option<i32>,
    pub small_contest_max_cost: Option<i32>,
    pub large_contest_max_entries: Option<i32>,
    pub large_contest_min_top_prize: Option<i32>,
    pub large_contest_max_cost: Option<i32>,
    pub winning_ratio: Option<i32>,
    pub game_count: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_contest_list::Entity")]
    BacktestContestList,
    #[sea_orm(has_many = "super::backtests::Entity")]
    Backtests,
}

impl Related<super::backtest_contest_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestContestList.def()
    }
}

impl Related<super::backtests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Backtests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
