//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "contest_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub contest_id: String,
    pub slate_id: Option<i32>,
    pub contest_name: Option<String>,
    pub max_entries: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub entry_fee: Option<f64>,
    pub total_entries: Option<i32>,
    pub complete: Option<String>,
    pub prize_pool: Option<i32>,
    pub top_prize: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cash_line: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub winning_score: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_contest_list::Entity")]
    BacktestContestList,
    #[sea_orm(has_many = "super::backtest_contest_summaries::Entity")]
    BacktestContestSummaries,
    #[sea_orm(has_many = "super::backtest_results::Entity")]
    BacktestResults,
    #[sea_orm(
        belongs_to = "super::slates::Entity",
        from = "Column::SlateId",
        to = "super::slates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Slates,
    #[sea_orm(has_many = "super::winning_charts::Entity")]
    WinningCharts,
}

impl Related<super::backtest_contest_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestContestList.def()
    }
}

impl Related<super::backtest_contest_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestContestSummaries.def()
    }
}

impl Related<super::backtest_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestResults.def()
    }
}

impl Related<super::slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slates.def()
    }
}

impl Related<super::winning_charts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WinningCharts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
