//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contests_pull")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Decimal(Some((12, 0)))", unique)]
    pub contest_id: Decimal,
    pub max_entries: i32,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub entry_fee: Decimal,
    pub contest_name: String,
    #[sea_orm(column_type = "Decimal(Some((12, 0)))")]
    pub total_entries: Decimal,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub prize_pool: Decimal,
    #[sea_orm(column_type = "Decimal(Some((21, 0)))")]
    pub start_time: Decimal,
    pub is_pulled: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
