//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub years_id: Option<i32>,
    pub dates: Option<Date>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_summaries::Entity")]
    BacktestSummaries,
    #[sea_orm(has_many = "super::dfs_players::Entity")]
    DfsPlayers,
    #[sea_orm(has_many = "super::slates::Entity")]
    Slates,
    #[sea_orm(
        belongs_to = "super::years::Entity",
        from = "Column::YearsId",
        to = "super::years::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Years,
}

impl Related<super::backtest_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestSummaries.def()
    }
}

impl Related<super::dfs_players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DfsPlayers.def()
    }
}

impl Related<super::slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Slates.def()
    }
}

impl Related<super::years::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Years.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
