//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dfn_live_hitters")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub slate_id: i32,
    pub player_name: String,
    pub salary: i32,
    pub position: String,
    pub team: String,
    pub opp: String,
    #[sea_orm(column_type = "Decimal(Some((8, 2)))")]
    pub projection: Decimal,
    pub duplicate: i32,
    pub locked: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::live_slates::Entity",
        from = "Column::SlateId",
        to = "super::live_slates::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LiveSlates,
}

impl Related<super::live_slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LiveSlates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
