//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "dfs_players")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_id: Option<i32>,
    pub player_id: Option<i32>,
    pub name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub position: Option<String>,
    pub dfs_position: Option<Vec<String>>,
    pub salary: Option<i32>,
    pub team_id: Option<i32>,
    pub opp_id: Option<i32>,
    pub game_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dates::Entity",
        from = "Column::DateId",
        to = "super::dates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dates,
    #[sea_orm(
        belongs_to = "super::games::Entity",
        from = "Column::GameId",
        to = "super::games::Column::GameId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Games,
    #[sea_orm(
        belongs_to = "super::players::Entity",
        from = "Column::PlayerId",
        to = "super::players::Column::PlayerId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Players,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::OppId",
        to = "super::teams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams2,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::TeamId",
        to = "super::teams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams1,
}

impl Related<super::dates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dates.def()
    }
}

impl Related<super::games::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Games.def()
    }
}

impl Related<super::players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Players.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
