//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub game_id: i32,
    pub date_id: Option<i32>,
    pub original_date_id: Option<i32>,
    pub game_time: Option<Time>,
    pub original_time: Option<Time>,
    pub status: Option<String>,
    pub complete: Option<String>,
    pub away_id: Option<i32>,
    pub home_id: Option<i32>,
    pub venue_id: Option<i32>,
    pub away_runs: Option<i32>,
    pub away_hits: Option<i32>,
    pub away_errors: Option<i32>,
    pub home_runs: Option<i32>,
    pub home_hits: Option<i32>,
    pub home_errors: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_files::Entity")]
    BacktestFiles,
    #[sea_orm(
        belongs_to = "super::dates::Entity",
        from = "Column::DateId",
        to = "super::dates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dates2,
    #[sea_orm(
        belongs_to = "super::dates::Entity",
        from = "Column::OriginalDateId",
        to = "super::dates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dates1,
    #[sea_orm(has_many = "super::dfs_players::Entity")]
    DfsPlayers,
    #[sea_orm(has_many = "super::hitter_game::Entity")]
    HitterGame,
    #[sea_orm(has_many = "super::pitcher_game::Entity")]
    PitcherGame,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::AwayId",
        to = "super::teams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams2,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::HomeId",
        to = "super::teams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams1,
    #[sea_orm(
        belongs_to = "super::venues::Entity",
        from = "Column::VenueId",
        to = "super::venues::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Venues,
    #[sea_orm(has_many = "super::weather::Entity")]
    Weather,
}

impl Related<super::backtest_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestFiles.def()
    }
}

impl Related<super::dfs_players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DfsPlayers.def()
    }
}

impl Related<super::hitter_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HitterGame.def()
    }
}

impl Related<super::pitcher_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PitcherGame.def()
    }
}

impl Related<super::venues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Venues.def()
    }
}

impl Related<super::weather::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Weather.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
