//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hitter_projections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backtest_id: Option<i32>,
    pub run: Option<i32>,
    #[sea_orm(column_name = "H001", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub h001: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::backtest_files::Entity",
        from = "Column::BacktestId",
        to = "super::backtest_files::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BacktestFiles,
}

impl Related<super::backtest_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
