//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "hitter_game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub game_id: Option<i32>,
    pub player_id: Option<i32>,
    pub team_id: Option<i32>,
    pub abs: Option<i32>,
    pub r: Option<i32>,
    pub hits: Option<i32>,
    pub doubles: Option<i32>,
    pub triples: Option<i32>,
    pub homeruns: Option<i32>,
    pub earned_runs: Option<i32>,
    pub unearned_runs: Option<i32>,
    pub rbi: Option<i32>,
    pub bb: Option<i32>,
    pub swings: Option<i32>,
    pub strikes: Option<i32>,
    pub foul: Option<i32>,
    pub missed: Option<i32>,
    pub strikes_looking: Option<i32>,
    pub tag_outs: Option<i32>,
    pub force_outs: Option<i32>,
    pub put_outs: Option<i32>,
    pub ground_balls: Option<i32>,
    pub fly_balls: Option<i32>,
    pub line_drives: Option<i32>,
    pub two_seam: Option<i32>,
    pub four_seam: Option<i32>,
    pub curveballs: Option<i32>,
    pub changeups: Option<i32>,
    pub cutters: Option<i32>,
    pub sliders: Option<i32>,
    pub sinkers: Option<i32>,
    pub splitters: Option<i32>,
    pub k: Option<i32>,
    pub sb: Option<i32>,
    pub caught_stealing: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sb_pct: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub avg: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub obp: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub slug: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub ops: Option<f64>,
    pub ibb: Option<i32>,
    pub hbp: Option<i32>,
    pub sac_bunts: Option<i32>,
    pub sac_fly: Option<i32>,
    pub tb: Option<i32>,
    pub xbh: Option<i32>,
    pub hit_double_plays: Option<i32>,
    pub hit_triple_plays: Option<i32>,
    pub ground_outs: Option<i32>,
    pub fly_outs: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub go_to_fo: Option<f64>,
    pub pitches_faced: Option<i32>,
    pub pa: Option<i32>,
    pub lob: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub innings: Option<f64>,
    pub total_chances: Option<i32>,
    pub fielder_tag_outs: Option<i32>,
    pub fielder_force_outs: Option<i32>,
    pub fielder_put_outs: Option<i32>,
    pub outs_faced: Option<i32>,
    pub assists: Option<i32>,
    pub errors: Option<i32>,
    pub fielder_double_plays: Option<i32>,
    pub fielder_triple_plays: Option<i32>,
    pub sb_allowed: Option<i32>,
    pub fielder_caught_stealing: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fielder_sb_pct: Option<f64>,
    pub passed_balls: Option<i32>,
    pub wild_pitches: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fielding_pct: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub range_factor: Option<f64>,
    pub game_started: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::games::Entity",
        from = "Column::GameId",
        to = "super::games::Column::GameId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Games,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::TeamId",
        to = "super::teams::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teams,
}

impl Related<super::games::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Games.def()
    }
}

impl Related<super::teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teams.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
