//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "live_slates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hitter_proj: Option<String>,
    pub pitcher_proj: Option<String>,
    pub number_of_games: Option<i32>,
    pub site: Option<String>,
    pub teams: Option<Vec<String>>,
    pub date_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dfn_live_hitters::Entity")]
    DfnLiveHitters,
    #[sea_orm(has_many = "super::dfn_live_pitchers::Entity")]
    DfnLivePitchers,
    #[sea_orm(has_many = "super::mlb_live_lineups::Entity")]
    MlbLiveLineups,
}

impl Related<super::dfn_live_hitters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DfnLiveHitters.def()
    }
}

impl Related<super::dfn_live_pitchers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DfnLivePitchers.def()
    }
}

impl Related<super::mlb_live_lineups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MlbLiveLineups.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
