//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "mlb_live_lineups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub slate_id: i32,
    pub p1: String,
    pub p2: String,
    pub c: String,
    pub first: String,
    pub second: String,
    pub third: String,
    pub ss: String,
    pub of1: String,
    pub of2: String,
    pub of3: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::live_slates::Entity",
        from = "Column::SlateId",
        to = "super::live_slates::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    LiveSlates,
}

impl Related<super::live_slates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LiveSlates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
