//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pitcher_projections")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backtest_id: Option<i32>,
    pub run: Option<i32>,
    #[sea_orm(column_name = "P001", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p001: Option<Decimal>,
    #[sea_orm(column_name = "P002", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p002: Option<Decimal>,
    #[sea_orm(column_name = "P003", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p003: Option<Decimal>,
    #[sea_orm(column_name = "P004", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p004: Option<Decimal>,
    #[sea_orm(column_name = "P005", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p005: Option<Decimal>,
    #[sea_orm(column_name = "P006", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p006: Option<Decimal>,
    #[sea_orm(column_name = "P007", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p007: Option<Decimal>,
    #[sea_orm(column_name = "P008", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p008: Option<Decimal>,
    #[sea_orm(column_name = "P009", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p009: Option<Decimal>,
    #[sea_orm(column_name = "P010", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p010: Option<Decimal>,
    #[sea_orm(column_name = "P011", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p011: Option<Decimal>,
    #[sea_orm(column_name = "P012", column_type = "Decimal(Some((8, 2)))", nullable)]
    pub p012: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::backtest_files::Entity",
        from = "Column::BacktestId",
        to = "super::backtest_files::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BacktestFiles,
}

impl Related<super::backtest_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
