//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "players")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub player_id: i32,
    pub player_name: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_files::Entity")]
    BacktestFiles,
    #[sea_orm(has_many = "super::dfs_players::Entity")]
    DfsPlayers,
}

impl Related<super::backtest_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestFiles.def()
    }
}

impl Related<super::dfs_players::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DfsPlayers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
