//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "slates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date_id: Option<i32>,
    pub slate: Option<DateTime>,
    pub number_of_games: Option<i32>,
    pub site: Option<String>,
    pub sport: Option<i32>,
    pub game_ids: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtest_contest_list::Entity")]
    BacktestContestList,
    #[sea_orm(has_many = "super::backtest_contest_summaries::Entity")]
    BacktestContestSummaries,
    #[sea_orm(has_many = "super::backtest_files::Entity")]
    BacktestFiles,
    #[sea_orm(has_many = "super::backtest_lineups::Entity")]
    BacktestLineups,
    #[sea_orm(has_many = "super::backtest_logs::Entity")]
    BacktestLogs,
    #[sea_orm(has_many = "super::contest_data::Entity")]
    ContestData,
    #[sea_orm(
        belongs_to = "super::dates::Entity",
        from = "Column::DateId",
        to = "super::dates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Dates,
}

impl Related<super::backtest_contest_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestContestList.def()
    }
}

impl Related<super::backtest_contest_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestContestSummaries.def()
    }
}

impl Related<super::backtest_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestFiles.def()
    }
}

impl Related<super::backtest_lineups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestLineups.def()
    }
}

impl Related<super::backtest_logs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestLogs.def()
    }
}

impl Related<super::contest_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestData.def()
    }
}

impl Related<super::dates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
