//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "teams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub teams: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hitter_game::Entity")]
    HitterGame,
    #[sea_orm(has_many = "super::pitcher_game::Entity")]
    PitcherGame,
}

impl Related<super::hitter_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HitterGame.def()
    }
}

impl Related<super::pitcher_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PitcherGame.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
