//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "weather")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub game_id: Option<i32>,
    pub weather_type: Option<String>,
    pub weather_description: Option<String>,
    pub wind_speed: Option<i32>,
    pub wind_direction: Option<i32>,
    pub temperature: Option<i32>,
    pub humidity: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::games::Entity",
        from = "Column::GameId",
        to = "super::games::Column::GameId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Games,
}

impl Related<super::games::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Games.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
