//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "winning_charts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub contest_id: Option<String>,
    pub payout: Option<i32>,
    pub min_finish: Option<i32>,
    pub max_finish: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub min_entry: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub max_entry: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contest_data::Entity",
        from = "Column::ContestId",
        to = "super::contest_data::Column::ContestId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ContestData,
}

impl Related<super::contest_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
