//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "years")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub years: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::backtests_complete::Entity")]
    BacktestsComplete,
    #[sea_orm(has_many = "super::dates::Entity")]
    Dates,
}

impl Related<super::backtests_complete::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BacktestsComplete.def()
    }
}

impl Related<super::dates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
